Review of code from Admission Trial
EnixWord/Review-Trial-Pair-Program pull request #1
Opened 2022-12-14 08:32 UTC by EnixWord

### **The following requirments has been made:**
- [ ]  Create a new empty repo.
- [ ] Copy my code from the project that I completed during the Admissions Trial.
- [ ] Play the role of the Code Reviewer.

2022-12-14 09:38 UTC, Favourezeugwa reviewed
Hi @EnixWord , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌❌❌

You have submitted a project, that has not been reviewed. Kindly review your code, a code reviewer will review your review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-15 16:54 UTC, EnixWord reviewed
# Changes required ♻️ 

Please check my comments below and make all required changes.

Submit for re-review when you're done.

Thanks 😁

2022-12-15 16:54 UTC, EnixWord commented on README.md
> + Review-Trial-Pair-Program
- [ ] I kindly suggest you to use only the name of the Repo you are working on in your README.md file. Hello Microverse Project doesn't seem to be part of your Repo name.
Using the appropriate name in your README.MD file helps you and other code users get a better insight to your code when re-using

2022-12-15 16:54 UTC, EnixWord commented on index.html
> +  </head>
- [ ] I think it will be nice if you add <meta> tags to your head tag. Metadata is used by browsers and search engines and other web services. Including them in your code makes your work more proffesional.

2022-12-15 16:58 UTC, EnixWord reviewed
.

2022-12-15 17:05 UTC, EnixWord reviewed
# Changes required ♻️ 

Please check my comments below and make all required changes.

Submit for re-review when you' re done.

Thanks 😁

2022-12-15 17:05 UTC, EnixWord commented on style.css
> +}
- [ ] Kindly link your .css file to the html file for proper style.

2022-12-15 17:29 UTC, jerryowusu commented on index.html
> +  </head>
Kindly provide a reason for making this change, it will help the student understand you better hence it will be easy to implement. :wink:

2022-12-15 17:30 UTC, jerryowusu commented on README.md
> + Review-Trial-Pair-Program
Kindly provide a reason for making this change, it will help the student understand you better hence it will be easy to implement. :wink:

2022-12-15 17:32 UTC, jerryowusu requested changes
Hi @EnixWord  

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

![almost there](https://user-images.githubusercontent.com/65233860/207928578-0452ce34-459e-47a1-a186-8c8f994919c0.gif)


## Highlights
Used GitHub inline comments :heavy_check_mark: 
Gave at least 2 review comments :heavy_check_mark: 

## Required Changes ♻️

- [ ] Kindly provide a reason for making this change, it will help the student understand you better hence it will be easy to implement. :wink: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-15 18:01 UTC, EnixWord commented on index.html
> +    <link rel="stylesheet" href="styles.css" />
- [ ] I kindly suggest you fix this link by making the href value  exactly same as the name of your css file. <link rel="stylesheet" href="style.css" />. Css file will not be properly linked to html file if there are spelling errors in the link in your <head> tag.

2022-12-15 18:12 UTC, Lizdev-05 approved these changes
Hi @EnixWord, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media0.giphy.com/media/bdaMVCP6bPIVWc0B3g/giphy.gif"/>
## Highlights

- Used GitHub inline comments ✅
- Polite tone was used ✅
- Reasons for the required changes were made known ✅

## Optional suggestions
I think it will be nice if you can make use of emojis 😊 and gifs in your review, it will make your review humanly friendly to the programmer 😎⚔️🟢😊

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-15 18:15 UTC, merged